jdkVersion="17"
customTools=["/extra-tools/clomonitor.sh"] # enable CLOMonitor scanning
tools=[] # do not include any other scanning tools

### code-lite (subset of code, recommended for secondary code repositories)
ignoreRules = [
	"Security: Signed Releases",
	"Security: Security Policy",
	"Security: Sbom",
	"Security: Maintained",
	"Security: Dependency Update Tool",
	"Security: Code Review",
	"Security: Branch Protection",
	"License: License Scanning",
	"Legal: Trademark Disclaimer",
	"Documentation: Website",
	"Documentation: Roadmap",
	"Documentation: Governance",
	"Documentation: Code Of Conduct",
	"Documentation: Changelog",
	"Documentation: Adopters",
	"Best Practices: Slack Presence",
	"Best Practices: Openssf Badge",
	"Best Practices: Github Discussions",
	"Best Practices: Community Meeting",
	"Best Practices: Artifacthub Badge",
	"Best Practices: Analytics"
]

### Ignore all tests
# ignoreRules = [
# 	"Security: Signed Releases",
# 	"Security: Security Policy",
# 	"Security: Sbom",
# 	"Security: Maintained",
# 	"Security: Dependency Update Tool",
# 	"Security: Code Review",
# 	"Security: Branch Protection",
# 	"License: License Spdx Id",
# 	"License: License Scanning",
# 	"License: License Approved",
# 	"Legal: Trademark Disclaimer",
# 	"Documentation: Website",
# 	"Documentation: Roadmap",
# 	"Documentation: Maintainers",
# 	"Documentation: Governance",
# 	"Documentation: Contributing",
# 	"Documentation: Code Of Conduct",
# 	"Documentation: Changelog",
# 	"Documentation: Adopters",
# 	"Best Practices: Slack Presence",
# 	"Best Practices: Recent Release",
# 	"Best Practices: Openssf Badge",
# 	"Best Practices: Github Discussions",
# 	"Best Practices: Dco",
# 	"Best Practices: Community Meeting",
# 	"Best Practices: Cla",
# 	"Best Practices: Artifacthub Badge",
# 	"Best Practices: Analytics"
# ]

