jdkVersion="17"
customTools=["/extra-tools/clomonitor.sh"] # enable CLOMonitor scanning
tools=[] # do not include any other scanning tools

### For lite tests
ignoreRules = ["Security: Signed Releases"]

